#!/usr/bin/env python3
"""Metadata and declared AI provenance checks, not account-safety certification."""
import json
import re
import sys

TOOL = "bw_audit"
VERSION = "1.0.0"

TRADEMARK_TERMS = ["world cup", "fifa", "olympics", "nba", "disney",
                   "harry potter", "official", "bts", "taylor swift"]
YEAR_RE = re.compile(r"\b(202[4-9]|2030)\b")
PROMO_TERMS = ["amazon", "kindle", "kdp", "bestseller", "best seller",
               "new york times", "free", "sale"]
KEYWORD_CHAR_LIMIT = 50
VELOCITY_RED = 14      # titles/week ≈ 2/day spam pattern
VELOCITY_WARN = 2

SEVERITY = {"green": 0, "yellow": 1, "red": 2}


def envelope(payload):
    return {"tool": TOOL, "version": VERSION, "ok": payload.get("overall") != "red", **payload}


def disclosure_block(uses_text, uses_images, uses_translation=False):
    lines = ["KDP AI-generated content disclosure — suggested answers:", "",
             "Q: Did you use AI tools to create any text, images, or translations in your book?",
             "A: Yes."]
    if uses_text:
        lines.append('Q: Text — "Some or all of the text in this book was generated by an AI-based tool." Select: Yes (AI-generated, with human review and editing).')
    if uses_images:
        lines.append('Q: Images — "Some or all of the images or cover art in this book were generated by an AI-based tool." Select: Yes (AI-generated, with human review and editing).')
    if uses_translation:
        lines.append("AI-generated translations: disclose the generated translation content.")
    lines += ["", "Note: AI-assisted work (brainstorming, grammar checking) does NOT require "
                  "disclosure; AI-generated content does. You remain responsible for accuracy and originality."]
    return "\n".join(lines)


def audit(cfg):
    # FAIL CLOSED: an audit with missing/invalid required inputs cannot pass.
    missing = []
    if not isinstance(cfg, dict):
        return envelope({"overall": "red", "overallLabel": "NOT READY", "categories": [],
                         "fixes": [], "disclosureText": None,
                         "errors": ["input must be a JSON object"]})
    if not str(cfg.get("title") or "").strip():
        missing.append("title is required and cannot be blank")
    kws = cfg.get("keywords")
    if not isinstance(kws, list) or not [k for k in kws if str(k).strip()]:
        missing.append("keywords: at least one non-empty keyword slot is required")
    cats = cfg.get("categories")
    if not isinstance(cats, list) or not [c for c in cats if str(c).strip()]:
        missing.append("categories: at least one category is required")
    for field in ("usesAiText", "usesAiImages", "usesAiTranslation"):
        if type(cfg.get(field)) is not bool:
            missing.append(f"{field} must be explicitly true or false; missing/null is UNKNOWN")
    if any(not isinstance(x, str) for x in (kws if isinstance(kws, list) else []) + (cats if isinstance(cats, list) else [])):
        missing.append("keywords and categories must contain text")
    if missing:
        return envelope({"overall": "red", "overallLabel": "NOT READY",
                         "categories": [], "fixes": missing, "disclosureText": None,
                         "errors": [f"missing required fields: {m}" for m in missing],
                         "note": "fail-closed: an unaudited or incomplete submission is never READY"})

    areas = []
    fixes = []

    # --- trademark & evergreen ---
    findings, level = [], "green"
    spots = [("title", cfg.get("title", "")), ("subtitle", cfg.get("subtitle", ""))]
    spots += [(f"keyword {i + 1}", k) for i, k in enumerate(cfg.get("keywords", []) or [])]
    spots += [("category", c) for c in cfg.get("categories", []) or []]
    for where, text in spots:
        low = text.lower()
        for term in TRADEMARK_TERMS:
            if re.search(r"(?<!\w)" + re.escape(term) + r"(?!\w)", low):
                findings.append(f'"{term}" in {where}: contextual rights/metadata review needed; this is not legal clearance')
                level = "yellow"
                fixes.append(f'Review the use of "{term}" in your {where} against the actual content and current guidance.')
    if not findings:
        findings.append("no trademarked terms or year stamps detected")
    areas.append({"id": "trademark", "label": "Trademark & Evergreen", "level": level, "findings": findings})

    # --- metadata lint ---
    findings, level = [], "green"
    keywords = [k.strip() for k in (cfg.get("keywords") or []) if k and k.strip()]
    for i, kw in enumerate(keywords):
        if len(kw) > KEYWORD_CHAR_LIMIT:
            findings.append(f"keyword {i + 1} is {len(kw)} chars (>{KEYWORD_CHAR_LIMIT}) — KDP may reject the whole set")
            level = "red"
            fixes.append(f"Shorten keyword {i + 1} to {KEYWORD_CHAR_LIMIT} chars or fewer.")
        low = kw.lower()
        for term in PROMO_TERMS:
            if re.search(r"(?<!\w)" + re.escape(term) + r"(?!\w)", low):
                findings.append(f'keyword {i + 1} contains "{term}" — competitor-brand/promotional terms are prohibited')
                if level == "green":
                    level = "yellow"
                fixes.append(f'Remove "{term}" from keyword {i + 1}.')
    tally = {}
    for kw in keywords:
        seen_here = set()
        for word in re.split(r"[^a-z0-9]+", kw.lower()):
            if len(word) < 4 or word in seen_here:
                continue
            seen_here.add(word)
            tally[word] = tally.get(word, 0) + 1
    dupes = [w for w, n in tally.items() if n >= 2]
    if dupes:
        findings.append(f"words repeated across keyword slots: {', '.join(dupes)} — duplicates waste slots")
        if level == "green":
            level = "yellow"
        fixes.append(f"Use each of {', '.join(repr(w) for w in dupes)} in only one slot.")
    if len(keywords) > 7:
        findings.append(f"{len(keywords)} keyword slots filled — verify the current channel slot limit")
        if level == "green":
            level = "yellow"
    if not findings:
        findings.append("keyword metadata is clean: length, repetition, and brand terms all pass")
    areas.append({"id": "metadata", "label": "Metadata Lint", "level": level, "findings": findings})

    # --- AI disclosure ---
    findings, level = [], "green"
    disclosure_text = None
    uses_text = bool(cfg.get("usesAiText"))
    uses_images = cfg["usesAiImages"]
    uses_translation = cfg["usesAiTranslation"]
    choice = cfg.get("disclosureChoice")
    if uses_text or uses_images or uses_translation:
        which = " and ".join(x for x, on in (("text", uses_text), ("images", uses_images), ("translations", uses_translation)) if on)
        if choice == "wont-disclose":
            findings.append('you selected "won\'t disclose" while using AI-generated content — required disclosure is unresolved')
            level = "red"
            fixes.append("Answer the KDP AI-disclosure question honestly — resolve the discrepancy before publication.")
        elif choice == "will-disclose":
            findings.append(f"AI-generated {which} will be disclosed — recorded for review against the current submission form")
            disclosure_text = disclosure_block(uses_text, uses_images, uses_translation)
        else:
            findings.append(f"AI-generated {which} flagged, but no disclosure decision made yet")
            level = "red"
            fixes.append("Decide the AI-disclosure answer before publishing (KDP asks during title setup).")
    else:
        findings.append('no AI-generated content flagged — answer "No" to the KDP AI question')
    areas.append({"id": "ai", "label": "AI Disclosure", "level": level, "findings": findings})

    areas.append({"id": "scope", "label": "Scope", "level": "green", "findings": [
        "Metadata/provenance check only. No account-safety or publication-readiness conclusion.",
        "Publishing limits must come from current reviewed official policy, not a title-count heuristic."]})

    overall = max((a["level"] for a in areas), key=lambda lv: SEVERITY[lv])
    label = {"red": "NOT READY", "yellow": "NEEDS REVIEW", "green": "METADATA CHECKED"}[overall]
    return envelope({"categories": areas, "overall": overall, "overallLabel": label,
                     "fixes": fixes, "disclosureText": disclosure_text, "publicationReady": False,
                     "policySource": "https://kdp.amazon.com/en_US/help/topic/G200672390",
                     "scope": "metadata_and_declared_AI_provenance_only"})


def main():
    raw = sys.argv[1] if len(sys.argv) > 1 else sys.stdin.read()
    json.dump(audit(json.loads(raw)), sys.stdout, indent=2, ensure_ascii=False)
    sys.stdout.write("\n")


if __name__ == "__main__":
    main()
